version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PGHOST=db               # Указываем имя сервиса базы данных
      - PGUSER=admin
      - PGPASSWORD=root
      - PGDATABASE=postgres
    volumes:
      - .:/app
    networks:
      - my-network

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: postgres     # Задаём базу данных
      POSTGRES_USER: admin      # Указываем пользователя
      POSTGRES_PASSWORD: root    # Задаём пароль
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network

volumes:
  pgdata:

networks:
  my-network:
